name: spotlas_feed
description: A small Flutter project done as a technical test for Spotlas.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  expandable_text: ^2.3.0
  flutter_svg: ^1.1.6
  equatable: ^2.0.5
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  spaces:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/response.json
